<x-layouts.app title="Exam Categories">
    <div class="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div><h2 class="text-2xl font-bold">Exam category library</h2><p class="mt-1 text-slate-500">Organize examinations without changing their subjects or history.</p></div>
        <a href="{{ route('admin.examination-categories.create') }}" class="inline-flex items-center justify-center gap-2 rounded-xl bg-brand-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-brand-600/20"><i data-lucide="plus" class="size-4"></i>New category</a>
    </div>

    <form class="surface mb-6 flex gap-3 p-4" method="GET"><label class="relative flex-1"><i data-lucide="search" class="absolute left-3 top-3.5 size-4 text-slate-400"></i><input name="search" value="{{ request('search') }}" placeholder="Search categories" class="focus-ring w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm dark:border-slate-700 dark:bg-slate-950"></label><button class="rounded-xl border border-slate-200 px-4 text-sm font-semibold dark:border-slate-700"><i data-lucide="filter" class="inline size-4"></i><span class="ml-2 hidden sm:inline">Filter</span></button></form>

    <div class="surface overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500 dark:bg-slate-800/50"><tr><th class="px-6 py-4">Category</th><th class="px-6 py-4">Status</th><th class="px-6 py-4">Examinations</th><th class="px-6 py-4">Description</th><th class="px-6 py-4"><span class="sr-only">Actions</span></th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-800">@forelse($categories as $category)<tr class="hover:bg-slate-50/70 dark:hover:bg-slate-800/30"><td class="px-6 py-4"><p class="font-semibold">{{ $category->name }}</p><p class="mt-1 font-mono text-xs text-slate-400">{{ $category->slug }}</p></td><td class="px-6 py-4"><span @class(['rounded-full px-2.5 py-1 text-xs font-bold', 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300' => $category->is_active, 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300' => ! $category->is_active])>{{ $category->is_active ? 'Active' : 'Inactive' }}</span></td><td class="px-6 py-4 text-slate-500">{{ $category->examinations_count }}</td><td class="max-w-sm px-6 py-4 text-slate-500">{{ str($category->description)->limit(90) ?: '—' }}</td><td class="px-6 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.examination-categories.edit', $category) }}" class="rounded-lg p-2 text-slate-500 hover:bg-brand-50 hover:text-brand-600"><i data-lucide="pencil" class="size-4"></i></a><form method="POST" action="{{ route('admin.examination-categories.destroy', $category) }}" data-confirm="This category will be permanently deleted. Examinations in this category will become uncategorized.">@csrf @method('DELETE')<button class="rounded-lg p-2 text-slate-500 hover:bg-rose-50 hover:text-rose-600"><i data-lucide="trash-2" class="size-4"></i></button></form></div></td></tr>@empty<tr><td colspan="5" class="px-6 py-14 text-center text-slate-500">No exam categories match this view. Create a category to organize examinations.</td></tr>@endforelse</tbody></table></div>@if($categories->hasPages())<div class="border-t border-slate-200 p-5 dark:border-slate-800">{{ $categories->links() }}</div>@endif</div>
</x-layouts.app>
