<x-layouts.app :title="$examination->title">
    @php($formatDuration = static function (int $seconds): string { $hours = intdiv($seconds, 3600); $minutes = intdiv($seconds % 3600, 60); $remainingSeconds = $seconds % 60; return $hours > 0 ? sprintf('%dh %02dm %02ds', $hours, $minutes, $remainingSeconds) : ($minutes > 0 ? sprintf('%dm %02ds', $minutes, $remainingSeconds) : $remainingSeconds.'s'); })
    <div class="mx-auto max-w-5xl"><a href="{{ route('instructor.leaderboards.index') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-brand-600"><i data-lucide="arrow-left" class="size-4"></i>All Leaderboards</a><p class="mt-5 text-sm font-semibold text-brand-600">{{ $examination->subject->name }} · {{ $participants }} participants</p><h2 class="mt-2 text-3xl font-bold">Leaderboard</h2>
        @if ($podium->isNotEmpty())
            <section class="mt-6 grid gap-4 sm:grid-cols-3" aria-label="Top three performers">@foreach ($podium as $entry)<article @class(['surface p-5 text-center', 'border-2 border-amber-400 bg-amber-50/60 dark:bg-amber-950/30 sm:-translate-y-2' => $entry->rank === 1, 'border border-slate-300 dark:border-slate-700' => $entry->rank !== 1])><span class="mx-auto grid size-12 place-items-center rounded-2xl bg-brand-100 text-lg font-black text-brand-700 dark:bg-brand-500/20 dark:text-brand-200">#{{ $entry->rank }}</span><h3 class="mt-4 truncate font-bold">{{ $entry->examinationAttempt->student->name }}</h3><p class="mt-2 text-sm text-slate-500">{{ $entry->obtained_marks }} / {{ $entry->maximum_marks }} · {{ $entry->percentage }}%</p><p class="mt-1 text-xs text-slate-400">{{ $formatDuration($entry->completion_seconds) }}</p></article>@endforeach</section>
        @endif
        <section class="surface mt-6 overflow-hidden"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead><tr><th class="p-4 text-left">Rank</th><th class="p-4 text-left">Student</th><th class="p-4 text-left">Score</th><th class="p-4 text-left">Percentage</th><th class="p-4 text-left">Completion</th><th class="p-4 text-left">Status</th></tr></thead><tbody>@forelse ($entries as $entry)<tr class="border-t dark:border-slate-800"><td class="p-4 font-bold">#{{ $entry->rank }}</td><td class="p-4">{{ $entry->examinationAttempt->student->name }}</td><td class="p-4">{{ $entry->obtained_marks }} / {{ $entry->maximum_marks }}</td><td class="p-4">{{ $entry->percentage }}%</td><td class="p-4">{{ $formatDuration($entry->completion_seconds) }}</td><td class="p-4"><span @class(['rounded-full px-3 py-1 text-xs font-bold', 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300' => $entry->passed, 'bg-rose-100 text-rose-700 dark:bg-rose-950/50 dark:text-rose-300' => ! $entry->passed])>{{ $entry->passed ? 'Pass' : 'Fail' }}</span></td></tr>@empty<tr><td colspan="6" class="p-12 text-center"><p class="font-semibold">No finalized results are available yet.</p><p class="mt-1 text-sm text-slate-500">Ranked participants will appear after students complete this examination.</p><a href="{{ route('instructor.examinations.index') }}" class="mt-4 inline-flex font-semibold text-brand-600">Back to My Examinations</a></td></tr>@endforelse</tbody></table></div></section>
    </div>
</x-layouts.app>
