<x-layouts.app :title="$examination->title">
    <div class="mx-auto max-w-3xl">
        <a href="{{ route('student.exams.index') }}" class="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-brand-600"><i data-lucide="arrow-left" class="size-4"></i>Available exams</a>
        <section class="surface mt-5 overflow-hidden">
            <div class="bg-slate-950 px-6 py-8 text-white sm:px-9"><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-bold uppercase tracking-wider text-brand-200">Examination instructions</span><h2 class="mt-4 text-3xl font-bold">{{ $examination->title }}</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-300">{{ $examination->description ?: 'Read the instructions carefully before beginning.' }}</p></div>
            <div class="p-6 sm:p-9"><dl class="grid gap-4 sm:grid-cols-3"><div class="rounded-2xl bg-brand-50 p-4 dark:bg-brand-500/10"><dt class="text-xs font-bold uppercase tracking-wider text-brand-700 dark:text-brand-300">Duration</dt><dd class="mt-2 text-xl font-bold">{{ $examination->duration_minutes }} minutes</dd></div><div class="rounded-2xl bg-brand-50 p-4 dark:bg-brand-500/10"><dt class="text-xs font-bold uppercase tracking-wider text-brand-700 dark:text-brand-300">Questions</dt><dd class="mt-2 text-xl font-bold">{{ $examination->questions()->count() }}</dd></div><div class="rounded-2xl bg-brand-50 p-4 dark:bg-brand-500/10"><dt class="text-xs font-bold uppercase tracking-wider text-brand-700 dark:text-brand-300">Attempts</dt><dd class="mt-2 text-xl font-bold">One only</dd></div></dl>
                <div class="mt-8"><h3 class="text-lg font-bold">Before you begin</h3><ul class="mt-4 space-y-3 text-sm leading-6 text-slate-600 dark:text-slate-300"><li class="flex gap-3"><i data-lucide="circle-check" class="mt-0.5 size-5 shrink-0 text-emerald-500"></i>Your timer begins immediately when you start and is enforced by the server.</li><li class="flex gap-3"><i data-lucide="circle-check" class="mt-0.5 size-5 shrink-0 text-emerald-500"></i>Choices save automatically. You can safely refresh and resume while time remains.</li><li class="flex gap-3"><i data-lucide="circle-check" class="mt-0.5 size-5 shrink-0 text-emerald-500"></i>When you submit or time expires, answers become read-only. Results are not calculated in this phase.</li></ul></div>
                <form method="POST" action="{{ route('student.attempts.start', $examination) }}" class="mt-8 border-t border-slate-100 pt-6 dark:border-slate-800">@csrf<button class="focus-ring inline-flex w-full items-center justify-center gap-2 rounded-xl bg-brand-600 px-5 py-3.5 text-sm font-bold text-white hover:bg-brand-700 sm:w-auto"><i data-lucide="play" class="size-4"></i>Start my one attempt</button><p class="mt-3 text-xs text-slate-500">Starting confirms that you understand these conditions.</p></form>
            </div>
        </section>
    </div>
</x-layouts.app>
