<x-layouts.app title="Overview">
    <section class="grid gap-6 xl:grid-cols-[1.5fr_1fr]">
        <div class="overflow-hidden rounded-3xl bg-gradient-to-br from-brand-700 via-indigo-700 to-violet-700 p-8 text-white shadow-xl shadow-indigo-900/20"><p class="text-sm font-semibold text-indigo-200">Welcome back</p><h2 class="mt-2 text-3xl font-bold">Ready for your next challenge, {{ str($student->name)->before(' ') }}?</h2><p class="mt-3 max-w-xl text-indigo-100">Your exam workspace is set up. Available examinations will appear here when Phase 3 content is published.</p><a href="{{ route('student.profile.edit') }}" class="mt-7 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-brand-700"><i data-lucide="user-round" class="size-4"></i>Complete profile</a></div>
        <div class="surface p-7"><div class="flex items-center justify-between"><div><p class="text-sm font-medium text-slate-500">Profile completion</p><p class="mt-1 text-3xl font-bold">{{ $profileCompletion }}%</p></div><span class="grid size-12 place-items-center rounded-2xl bg-emerald-50 text-emerald-600 dark:bg-emerald-950/40"><i data-lucide="badge-check" class="size-6"></i></span></div><div class="mt-6 h-2.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div class="h-full rounded-full bg-gradient-to-r from-brand-500 to-emerald-400" style="width: {{ $profileCompletion }}%"></div></div><p class="mt-4 text-sm text-slate-500">Add contact details and a short bio to finish your profile.</p></div>
    </section>
    <section class="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">
        @foreach ([['Exams Completed', $resultStatistics['completed'], 'clipboard-check'], ['Passed', $resultStatistics['passed'], 'circle-check'], ['Failed', $resultStatistics['failed'], 'circle-x'], ['Average Percentage', number_format((float) $resultStatistics['average'], 1).'%', 'chart-no-axes-column']] as [$label, $value, $icon])
            <article class="surface p-6"><div class="flex items-center justify-between"><span class="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10"><i data-lucide="{{ $icon }}" class="size-5"></i></span><span class="text-3xl font-bold">{{ $value }}</span></div><p class="mt-5 text-sm font-medium text-slate-500">{{ $label }}</p></article>
        @endforeach
    </section>
    <section class="surface mt-8 overflow-hidden"><div class="flex items-center justify-between border-b border-slate-200 p-6 dark:border-slate-800"><div><h3 class="font-bold">Recent Results</h3><p class="mt-1 text-sm text-slate-500">Your five most recently finalized examinations.</p></div><a href="{{ route('student.results.index') }}" class="text-sm font-semibold text-brand-600">View all</a></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse ($recentResults as $result)<div class="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div class="min-w-0 flex-1"><p class="truncate font-semibold">{{ $result->examinationAttempt->examination->title }}</p><p class="mt-1 text-sm text-slate-500">Score {{ $result->obtained_marks }} / {{ $result->maximum_marks }} · {{ $result->percentage }}%</p></div><span @class(['w-fit rounded-full px-3 py-1 text-xs font-bold', 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300' => $result->passed, 'bg-rose-100 text-rose-700 dark:bg-rose-950/50 dark:text-rose-300' => ! $result->passed])>{{ $result->passed ? 'Pass' : 'Fail' }}</span><a href="{{ route('student.results.show', $result) }}" class="text-sm font-semibold text-brand-600">View Result</a></div>@empty<div class="p-10 text-center"><p class="font-semibold">No results yet</p><p class="mt-1 text-sm text-slate-500">Finalized examination results will appear here.</p></div>@endforelse</div></section>
</x-layouts.app>
