@php($answers = $attempt->answers->keyBy('question_id'))
<x-layouts.app :title="$attempt->examination->title">
    <div x-data="examAttempt({ expiresAt: {{ $attempt->expires_at->getTimestampMs() }}, token: '{{ csrf_token() }}', submitUrl: '{{ route('student.attempts.submit', $attempt) }}', answerUrls: @js($questions->mapWithKeys(fn ($question) => [$question->id => route('student.attempts.answers.update', [$attempt, $question])])), versions: @js($answers->mapWithKeys(fn ($answer) => [$answer->question_id => $answer->version])) })" class="mx-auto max-w-5xl">
        <div class="sticky top-20 z-20 mb-6 flex flex-wrap items-center gap-4 rounded-2xl border border-slate-200 bg-white/95 p-4 shadow-sm backdrop-blur dark:border-slate-800 dark:bg-slate-900/95"><div class="min-w-0"><p class="text-xs font-bold uppercase tracking-wider text-brand-600">In progress</p><h2 class="truncate text-lg font-bold">{{ $attempt->examination->title }}</h2></div><div class="ml-auto rounded-xl bg-slate-950 px-4 py-2 text-right text-white"><p class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Time remaining</p><p class="font-mono text-xl font-bold" :class="{ 'text-rose-300': remaining <= 60 }" x-text="formattedRemaining"></p></div><button type="button" @click="confirmSubmit" :disabled="submitting" class="focus-ring rounded-xl bg-rose-600 px-4 py-3 text-sm font-bold text-white hover:bg-rose-700 disabled:opacity-60"><span x-text="submitting ? 'Submitting…' : 'Submit exam'"></span></button></div>
        <div class="mb-5 flex flex-wrap gap-2">@foreach($questions as $index => $question)<a href="#question-{{ $question->id }}" class="grid size-9 place-items-center rounded-lg text-xs font-bold" :class="selected[{{ $question->id }}] ? 'bg-brand-600 text-white' : 'bg-slate-200 text-slate-600 dark:bg-slate-800 dark:text-slate-300'">{{ $index + 1 }}</a>@endforeach</div>
        <div class="space-y-5">@foreach($questions as $index => $question)<article id="question-{{ $question->id }}" class="surface scroll-mt-32 p-5 sm:p-7"><div class="flex gap-4"><span class="grid size-9 shrink-0 place-items-center rounded-xl bg-brand-50 text-sm font-bold text-brand-700 dark:bg-brand-500/10 dark:text-brand-300">{{ $index + 1 }}</span><div class="min-w-0 flex-1"><h3 class="text-base font-bold leading-7">{{ $question->question_text }}</h3><div class="mt-5 grid gap-3">@foreach(['a' => $question->option_a, 'b' => $question->option_b, 'c' => $question->option_c, 'd' => $question->option_d] as $option => $label)<label class="flex cursor-pointer items-center gap-3 rounded-xl border p-4 transition" :class="selected[{{ $question->id }}] === '{{ $option }}' ? 'border-brand-500 bg-brand-50 dark:bg-brand-500/10' : 'border-slate-200 hover:border-brand-300 dark:border-slate-800'"><input type="radio" name="question_{{ $question->id }}" value="{{ $option }}" class="size-4 text-brand-600" @checked(($answers[$question->id]->selected_option ?? null) === $option) @change="saveAnswer({{ $question->id }}, '{{ $option }}')"><span class="grid size-7 place-items-center rounded-lg bg-slate-100 text-xs font-bold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{{ strtoupper($option) }}</span><span class="text-sm font-medium">{{ $label }}</span></label>@endforeach</div><p class="mt-3 text-xs text-slate-400" x-text="status[{{ $question->id }}] || ''"></p></div></div></article>@endforeach</div>
        <div class="mt-8 flex justify-end"><button type="button" @click="confirmSubmit" :disabled="submitting" class="focus-ring rounded-xl bg-brand-600 px-5 py-3 text-sm font-bold text-white hover:bg-brand-700">Submit exam</button></div>
    </div>
</x-layouts.app>
