<x-layouts.app title="Analytics">
    <div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div><h2 class="text-2xl font-bold">Analytics</h2><p class="mt-1 text-slate-500">Aggregate reporting from finalized, persisted examination results.</p></div>
        <a href="{{ route('admin.results.index') }}" class="w-fit text-sm font-semibold text-brand-600">View individual results</a>
    </div>

    <form method="GET" action="{{ route('admin.analytics.index') }}" class="surface mb-6 grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4">
        <label class="grid gap-2 text-sm font-medium text-slate-700 dark:text-slate-200"><span>Examination</span><select name="examination_id" class="focus-ring rounded-xl border border-slate-300 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950"><option value="">All examinations</option>@foreach ($examinations as $examination)<option value="{{ $examination->id }}" @selected((int) ($filters['examination_id'] ?? 0) === $examination->id)>{{ $examination->title }}</option>@endforeach</select></label>
        <label class="grid gap-2 text-sm font-medium text-slate-700 dark:text-slate-200"><span>Subject</span><select name="subject_id" class="focus-ring rounded-xl border border-slate-300 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950"><option value="">All subjects</option>@foreach ($subjects as $subject)<option value="{{ $subject->id }}" @selected((int) ($filters['subject_id'] ?? 0) === $subject->id)>{{ $subject->name }}</option>@endforeach</select></label>
        <label class="grid gap-2 text-sm font-medium text-slate-700 dark:text-slate-200"><span>Result status</span><select name="passed" class="focus-ring rounded-xl border border-slate-300 bg-white px-4 py-3 dark:border-slate-700 dark:bg-slate-950"><option value="">Pass and fail</option><option value="1" @selected(($filters['passed'] ?? null) === '1')>Pass</option><option value="0" @selected(($filters['passed'] ?? null) === '0')>Fail</option></select></label>
        <div class="flex items-end gap-3"><x-primary-button class="flex-1"><i data-lucide="filter" class="size-4"></i>Apply Filters</x-primary-button><a href="{{ route('admin.analytics.index') }}" class="rounded-xl px-4 py-3 text-sm font-semibold text-slate-500 hover:text-slate-900 dark:hover:text-white">Clear</a></div>
    </form>

    <section class="grid gap-5 sm:grid-cols-2 xl:grid-cols-5">
        @foreach ([['Total graded results', number_format($summary['totalResults']), 'chart-no-axes-column'], ['Students with results', number_format($summary['uniqueStudents']), 'users'], ['Examinations with results', number_format($summary['examinationsWithResults']), 'clipboard-check'], ['Pass rate', number_format($summary['passRate'], 1).'%', 'circle-check'], ['Average performance', number_format($summary['averagePercentage'], 1).'%', 'trending-up']] as [$label, $value, $icon])
            <article class="surface p-6"><div class="flex items-center justify-between gap-3"><span class="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10"><i data-lucide="{{ $icon }}" class="size-5"></i></span><span class="text-2xl font-bold">{{ $value }}</span></div><p class="mt-5 text-sm font-medium text-slate-500">{{ $label }}</p></article>
        @endforeach
    </section>

    @if ($summary['totalResults'] === 0)
        <section class="surface mt-8 p-10 text-center"><i data-lucide="chart-pie" class="mx-auto size-10 text-slate-400"></i><h3 class="mt-4 font-bold">No results match these filters</h3><p class="mt-1 text-sm text-slate-500">Try clearing a filter or return after examinations have been finalized.</p></section>
    @else
        <section x-data="analyticsCharts(@js(['passFail' => ['passed' => $summary['passedResults'], 'failed' => $summary['failedResults']], 'scoreDistribution' => $scoreDistribution, 'trend' => $trend]))" class="mt-8 grid gap-5 xl:grid-cols-2">
            <article class="surface p-6"><div><h3 class="font-bold">Pass / fail distribution</h3><p class="mt-1 text-sm text-slate-500">{{ number_format($summary['passedResults']) }} passed and {{ number_format($summary['failedResults']) }} failed persisted results.</p></div><div x-ref="passFail" class="mt-5 min-h-72"></div></article>
            <article class="surface p-6"><div><h3 class="font-bold">Performance distribution</h3><p class="mt-1 text-sm text-slate-500">Results grouped by their persisted percentage.</p></div><div x-ref="scoreDistribution" class="mt-5 min-h-72"></div><div class="mt-4 grid grid-cols-2 gap-2 text-xs text-slate-500 sm:grid-cols-3">@foreach ($scoreDistribution as $bucket)<span>{{ $bucket['label'] }}: {{ $bucket['count'] }}</span>@endforeach</div></article>
            <article class="surface p-6 xl:col-span-2"><div><h3 class="font-bold">Average performance over time</h3><p class="mt-1 text-sm text-slate-500">Monthly average of persisted result percentages.</p></div><div x-ref="trend" class="mt-5 min-h-72"></div><div class="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs text-slate-500">@foreach ($trend as $period)<span>{{ $period['label'] }}: {{ number_format($period['averagePercentage'], 1) }}%</span>@endforeach</div></article>
        </section>
    @endif

    <section class="surface mt-8 overflow-hidden"><div class="border-b border-slate-200 p-6 dark:border-slate-800"><h3 class="font-bold">Examination performance</h3><p class="mt-1 text-sm text-slate-500">Results and percentages are calculated per examination.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left dark:bg-slate-800"><tr><th class="p-4">Examination</th><th class="p-4">Subject</th><th class="p-4">Results</th><th class="p-4">Average</th><th class="p-4">Passed</th><th class="p-4">Failed</th><th class="p-4">Pass rate</th></tr></thead><tbody>@forelse ($examinationPerformance as $examination)<tr class="border-t border-slate-100 dark:border-slate-800"><td class="p-4 font-semibold">{{ $examination['title'] }}</td><td class="p-4 text-slate-500">{{ $examination['subject'] }}</td><td class="p-4">{{ $examination['resultCount'] }}</td><td class="p-4">{{ number_format($examination['averagePercentage'], 1) }}%</td><td class="p-4 text-emerald-600">{{ $examination['passedResults'] }}</td><td class="p-4 text-rose-600">{{ $examination['failedResults'] }}</td><td class="p-4">{{ number_format($examination['passRate'], 1) }}%</td></tr>@empty<tr><td colspan="7" class="p-12 text-center text-slate-500">No examination performance is available for these filters.</td></tr>@endforelse</tbody></table></div></section>

    <section class="surface mt-8 overflow-hidden"><div class="border-b border-slate-200 p-6 dark:border-slate-800"><h3 class="font-bold">Subject performance</h3><p class="mt-1 text-sm text-slate-500">Aggregate results across examinations in each subject.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-slate-50 text-left dark:bg-slate-800"><tr><th class="p-4">Subject</th><th class="p-4">Results</th><th class="p-4">Students</th><th class="p-4">Average</th><th class="p-4">Pass rate</th></tr></thead><tbody>@forelse ($subjectPerformance as $subject)<tr class="border-t border-slate-100 dark:border-slate-800"><td class="p-4 font-semibold">{{ $subject['name'] }}</td><td class="p-4">{{ $subject['resultCount'] }}</td><td class="p-4">{{ $subject['uniqueStudents'] }}</td><td class="p-4">{{ number_format($subject['averagePercentage'], 1) }}%</td><td class="p-4">{{ number_format($subject['passRate'], 1) }}%</td></tr>@empty<tr><td colspan="5" class="p-12 text-center text-slate-500">No subject performance is available for these filters.</td></tr>@endforelse</tbody></table></div></section>
</x-layouts.app>
