<x-layouts.app title="Dashboard">
    <section class="overflow-hidden rounded-3xl bg-gradient-to-r from-brand-700 via-indigo-700 to-violet-700 p-7 text-white shadow-xl shadow-indigo-900/20 sm:p-9">
        <span class="inline-flex items-center gap-2 rounded-full bg-white/15 px-3 py-1 text-xs font-bold uppercase tracking-wider"><i data-lucide="presentation" class="size-4"></i>Instructor</span>
        <h2 class="mt-5 text-3xl font-bold">Welcome, {{ str($instructor->name)->before(' ') }}.</h2>
        <p class="mt-2 max-w-2xl text-indigo-100">Your assigned subjects, private Question Bank, and examination workspace are ready. Results tools will arrive in later Phase 7 sub-phases.</p>
        <a href="{{ route('instructor.examinations.index') }}" class="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-bold text-brand-700"><i data-lucide="clipboard-check" class="size-4"></i>Open My Examinations</a>
    </section>
    <section class="mt-7 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">
        <a href="{{ route('instructor.subjects.index') }}" class="surface p-6 transition hover:-translate-y-0.5 hover:shadow-lg"><div class="flex items-center justify-between"><span class="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10"><i data-lucide="book-open" class="size-5"></i></span><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-300">Available</span></div><h3 class="mt-5 font-bold">My Subjects</h3><p class="mt-1 text-sm text-slate-500">Review the subjects assigned to your account.</p></a>
        <a href="{{ route('instructor.questions.index') }}" class="surface p-6 transition hover:-translate-y-0.5 hover:shadow-lg"><div class="flex items-center justify-between"><span class="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10"><i data-lucide="circle-help" class="size-5"></i></span><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-300">Available</span></div><h3 class="mt-5 font-bold">Question Bank</h3><p class="mt-1 text-sm text-slate-500">Manage your private questions by assigned subject.</p></a>
        <a href="{{ route('instructor.examinations.index') }}" class="surface p-6 transition hover:-translate-y-0.5 hover:shadow-lg"><div class="flex items-center justify-between"><span class="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10"><i data-lucide="clipboard-check" class="size-5"></i></span><span class="rounded-full bg-brand-50 px-3 py-1 text-xs font-bold text-brand-600 dark:bg-brand-500/10 dark:text-brand-300">{{ $ownedExaminationCount }} owned</span></div><h3 class="mt-5 font-bold">My Examinations</h3><p class="mt-1 text-sm text-slate-500">Create and manage examination metadata and schedules.</p></a>
        @foreach ([['Results', 'chart-no-axes-column'], ['Leaderboard', 'trophy']] as [$label, $icon])
            <article class="surface p-6"><div class="flex items-center justify-between"><span class="grid size-11 place-items-center rounded-xl bg-brand-50 text-brand-600 dark:bg-brand-500/10"><i data-lucide="{{ $icon }}" class="size-5"></i></span><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-500 dark:bg-slate-800 dark:text-slate-300">Coming Soon</span></div><h3 class="mt-5 font-bold">{{ $label }}</h3><p class="mt-1 text-sm text-slate-500">Available in a later instructor sub-phase.</p></article>
        @endforeach
    </section>
</x-layouts.app>
